In [5]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
import numpy as np

In [6]:
def read_csv_data():
    df = pd.read_csv("spam_raw_data.csv",header=None)#imput spam data
    X_data = df.iloc[:,0:57]
    y_data = df.iloc[:,[57]]
    return np.array(X_data),np.array(y_data)
    #Define a function to imput spam data

In [7]:
if __name__ == "__main__":
    X_data,y_data = read_csv_data()
    y_data = np.array([x[0] for x in y_data])
    X_train_org, X_test_org, y_train_org, y_test_org = train_test_split(X_data, y_data, test_size=0.33, random_state=42)
    #Randomly divide data into train sets and test sets
    lr = LogisticRegression(solver='liblinear')
    #Classify spam by logistic regression classification
    kf = KFold(n_splits=5,shuffle=True)
    #K-Fold cross validation function
    #K-Fold cross validation
    for train_index, test_index in kf.split(X_train_org):
        X_train, X_test = X_train_org[train_index], X_train_org[test_index]
        y_train, y_test = y_train_org[train_index], y_train_org[test_index]
        #Divide train sets into 5
        lr.fit(X_train,y_train)
        #Classify the train sets
        y_pred = lr.predict(X_test)  
        # y_test <--> y_true #Predict function
        # print(classification_report(y_test,y_pred))
        print(confusion_matrix(y_test,y_pred,labels=[0,1]))
        t = np.sum(y_pred == y_test) / len(y_test)
        print((1-t))
        #Output error rates
        cm = confusion_matrix(y_test,y_pred,labels=[0,1])
        TP, TN, FN, FP = cm[0,0], cm[1,1], cm[0,1], cm[1,0]
        print(TP / (TP+FP))
        #Output precision
        print(TP / (TP+FN))
        #Output recall

[[361  21]
 [ 29 206]]
0.08103727714748787
0.9256410256410257
0.9450261780104712
[[354  25]
 [ 20 218]]
0.07293354943273911
0.946524064171123
0.9340369393139841
[[366  17]
 [ 38 195]]
0.0892857142857143
0.905940594059406
0.9556135770234987
[[363  20]
 [ 27 206]]
0.07629870129870131
0.9307692307692308
0.9477806788511749
[[363  12]
 [ 30 211]]
0.06818181818181823
0.9236641221374046
0.968
