In [1]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
import numpy as np

In [2]:
def read_csv_data():
    df = pd.read_csv("spam_raw_data.csv",header=None)#imput spam data
    X_data = df.iloc[:,0:57]
    y_data = df.iloc[:,[57]]
    return np.array(X_data),np.array(y_data)
    #Define a function to imput spam data

In [3]:
if __name__ == "__main__":
    X_data,y_data = read_csv_data()
    y_data = np.array([x[0] for x in y_data])
    X_train_org, X_test_org, y_train_org, y_test_org = train_test_split(X_data, y_data, test_size=0.33, random_state=42)
    #Randomly divide data into train sets and test sets
    lr = LogisticRegression(solver='liblinear')
    #Classify spam by logistic regression classification
    kf = KFold(n_splits=5,shuffle=True)
    #K-Fold cross validation function
    #K-Fold cross validation
    for train_index, test_index in kf.split(X_train_org):
        X_train, X_test = X_train_org[train_index], X_train_org[test_index]
        y_train, y_test = y_train_org[train_index], y_train_org[test_index]
        #Divide train sets into 5
        lr.fit(X_train,y_train)
        #Classify the train sets
        y_pred = lr.predict(X_test)  
        # y_test <--> y_true #Predict function
        # print(classification_report(y_test,y_pred))
        print(confusion_matrix(y_test,y_pred,labels=[0,1]))
        t = np.sum(y_pred == y_test) / len(y_test)
        print((1-t))
        #output error rates

[[367  19]
 [ 22 209]]
0.06645056726094001
[[361  18]
 [ 39 199]]
0.09238249594813619
[[367  15]
 [ 27 207]]
0.06818181818181823
[[349  27]
 [ 34 206]]
0.09902597402597402
[[352  27]
 [ 31 206]]
0.0941558441558441
